In [1]:
class Mobile:

    def __init__(self):
        print("This message is from Constructor Method")

    def receive_message(self):
        print("Receive message using Mobile")

    def send_message(self):
        print("Send message using Mobile")


def main():
    nokia = Mobile()
    nokia.receive_message()
    nokia.send_message()


if __name__ == "__main__":
    main()

This message is from Constructor Method
Receive message using Mobile
Send message using Mobile


In [4]:
import math

class ArcLength:
    def __init__(self):
        self.radius = 0
        self.angle = 0

    def calculate_arc_length(self):
        result = 2 * math.pi * self.radius * self.angle / 360
        print(f"Length of an Arc is {result}")

al = ArcLength()
al.radius = 99
al.angle = 79
print(f"Angle is {al.angle}")
print(f"Radius is {al.radius}")
al.calculate_arc_length()

Angle is 79
Radius is 99
Length of an Arc is 136.50220079847654


In [5]:
class Birds:

    def __init__(self, bird_name):
        self.bird_name = bird_name

    def flying_birds(self):
        print(f"{self.bird_name} flies above clouds")

    def non_flying_birds(self):
        print(f"{self.bird_name} is the national bird of Australia")

def main():
    vulture = Birds("Griffon Vulture")
    crane = Birds("Common Crane")
    emu = Birds("Emu")
    vulture.flying_birds()
    crane.flying_birds()
    emu.non_flying_birds()

if __name__ == "__main__":
    main()

Griffon Vulture flies above clouds
Common Crane flies above clouds
Emu is the national bird of Australia


In [7]:
class BankAccount:

    def __init__(self, name):
        self.user_name = name
        self.balance = 0.0

    def show_balance(self):
        print(f"{self.user_name} has a balance of {self.balance} dollars")

    def withdraw_money(self, amount):
        if amount > self.balance:
            print("You don't have sufficient funds in your account")
        else:
            self.balance -= amount
            print(f"{self.user_name} has withdrawn an amount of {self.balance} dollars")

    def deposit_money(self, amount):
        self.balance += amount
        print(f"{self.user_name} has deposited an amount of {self.balance} dollars")


def main():
    savings_account = BankAccount("Olivia")
    savings_account.deposit_money(10000)
    savings_account.show_balance()
    savings_account.withdraw_money(50000)
    savings_account.show_balance()


if __name__ == "__main__":
    main()

Olivia has deposited an amount of 10000.0 dollars
Olivia has a balance of 10000.0 dollars
You don't have sufficient funds in your account
Olivia has a balance of 10000.0 dollars


In [9]:
class Track:
    def __init__(self, song, artist):
        self.song = song
        self.artist = artist


def print_track_info(vocalist):
    vocalist.song="BAC"
    print(f"Song is '{vocalist.song}'")
    print(f"Artist is '{vocalist.artist}'")


singer = Track("The First Time Ever I Saw Your Face", "Roberta Flack")
print(f"Song is '{singer.song}'")



print_track_info(singer)

Song is 'The First Time Ever I Saw Your Face'
Song is 'BAC'
Artist is 'Roberta Flack'


In [1]:
class PrivateDemo:
    def __init__(self):
        self.nonprivateinstance = "I'm not private instance"
        self.__privateinstance = "I'm private instance"

    def display_privateinstance(self):
        print(f"{self.__privateinstance} used within method of a class")


def main():
    demo = PrivateDemo()
    print("Invoke Method having private instance")
    (demo.display_privateinstance())
    print("Invoke non-private instance variable")
    print(demo.nonprivateinstance)
    print("Get attributes of object")
    print(demo.__dict__)
    print("Trying to access private instance variable outside the class results in error")
    print(demo.__privateinstance)

if __name__ == "__main__":
        main()

Invoke Method having private instance
I'm private instance used within method of a class
Invoke non-private instance variable
I'm not private instance
Get attributes of object
{'nonprivateinstance': "I'm not private instance", '_PrivateDemo__privateinstance': "I'm private instance"}
Trying to access private instance variable outside the class results in error


AttributeError: 'PrivateDemo' object has no attribute '__privateinstance'

In [5]:
class Complex:
    def __init__(self, real, imaginary):
        self.real = real
        self.imaginary = imaginary

    def __add__(self, other):
        return Complex(self.real + other.real, self.imaginary + other.imaginary)

    def __str__(self):
        return f"{self.real} + {self.imaginary}i"


def main():
    complex_number_1 = Complex(4, 5)
    complex_number_2 = Complex(2, 3)
    complex_number_sum = complex_number_1 + complex_number_2
    print(f"Addition of two complex numbers {complex_number_1} and {complex_number_2} is {complex_number_sum}")


if __name__ == "__main__":
    main()

Addition of two complex numbers 4 + 5i and 2 + 3i is 6 + 8i


In [5]:
complex(4,3)

(4+3j)

In [7]:
class course:
    def __init__(self, id, name):
        self.id = id
        self.name = name


def course_info(syllabus):
    syllabus.id="B.Tech."
    print(f"id is '{syllabus.id}'")
    print(f"syllabus is '{syllabus.name}'")

syllabus = course("Python Data Analytics", "IIIsem")
print(f"Name is '{syllabus.id}'")

course_info(syllabus)

Name is 'Python Data Analytics'
id is 'B.Tech.'
syllabus is 'IIIsem'


In [1]:
import numpy as np
A=np.arange(9).reshape(3,3)
[A1,A2,A3]=np.split(A,[1,3],axis=0)
print(A1)
print(A2)
print(A3)

[[0 1 2]]
[[3 4 5]
 [6 7 8]]
[]


In [4]:
B=np.arange(4).reshape(2,2)
C=np.ones(4).reshape(2,2)
B
C

array([[1., 1.],
       [1., 1.]])

In [7]:
np.vstack((B,C))

array([[0., 1.],
       [2., 3.],
       [1., 1.],
       [1., 1.]])

In [15]:
A=np.ones(4).reshape(2,2)
A.shape=(1,4)
print(A)



array([[1., 1., 1., 1.]])