In [1]:
import numpy as np
arr=np.array([1, 2, 3, 4])
print(arr.ndim)

1


In [2]:
g = np.array([['a', 'b'],['c', 'd']])
g.dtype.name

'str32'

In [3]:
import numpy as np
f = np.array([[1, 2, 3],[4, 5, 6]], dtype='complex')
print(f)
print(f.dtype)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
complex128


In [4]:
import numpy as np
data = np.genfromtxt('sample.csv', delimiter=',', dtype=('i4','i2','a12','a1'), names=True)
data

array([(210962052,  1, b'SIDDHANT KUM', b'B'),
       (210962055,  2, b'NANDHANA SAN', b'B'),
       (210962108,  3, b'SEVVA NITHIN', b'B'),
       (210962176,  4, b'SAI HARSHINI', b'B'),
       (220962001,  5, b'BHARATH KUMA', b'B'),
       (220962003,  6, b'SUCHIT GUPTA', b'B'),
       (220962004,  7, b'VARUN PRABHU', b'B'),
       (220962012,  8, b'YASHAS S', b'B'),
       (220962013,  9, b'NIKHIL NAIR', b'B'),
       (220962021, 10, b'ARNAV SANJAY', b'B'),
       (220962026, 11, b'AKULA OMKAR', b'B'),
       (220962032, 12, b'ARHAM DUGAR', b'B')],
      dtype=[('Reg_No', '<i4'), ('Roll_No', '<i2'), ('Student_Name', 'S12'), ('Grade', 'S1')])

In [5]:
data['Roll_No']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int16)

In [6]:
data['Student_Name']

array([b'SIDDHANT KUM', b'NANDHANA SAN', b'SEVVA NITHIN', b'SAI HARSHINI',
       b'BHARATH KUMA', b'SUCHIT GUPTA', b'VARUN PRABHU', b'YASHAS S',
       b'NIKHIL NAIR', b'ARNAV SANJAY', b'AKULA OMKAR', b'ARHAM DUGAR'],
      dtype='|S12')

In [7]:
data[1]

(210962055, 2, b'NANDHANA SAN', b'B')

In [8]:
import pandas as pd

In [9]:
import numpy as np
A=np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
import numpy as np
[A1,A2,A3] = np.split(A,[0,3],axis=0)
A1,A2,A3
##For example, [2, 3] would, for axis=0, result in
#ary[:2]
#ary[2:3]
#ary[3:]

(array([], shape=(0, 4), dtype=int32),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]))

In [11]:
import pandas as pd
s1=pd.Series([ 1,2,6,10,12])
s1

0     1
1     2
2     6
3    10
4    12
dtype: int64

In [12]:
s2=pd.Series([ 1,2,6,10,12], index=['a','b','c','d','e'])
s2

a     1
b     2
c     6
d    10
e    12
dtype: int64

In [13]:
s2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [14]:
s2.values

array([ 1,  2,  6, 10, 12], dtype=int64)

In [15]:
s2['b']

2

In [16]:
s2['a':'c']

a    1
b    2
c    6
dtype: int64

In [17]:
s2[3]

C:\Users\YASH SRIVASTAVA\AppData\Local\Temp\ipykernel_24608\2948264381.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[3]


10

In [18]:
serd = pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [19]:
serd.unique()
serd['white':'green']

white    1
white    0
blue     2
green    1
green    2
dtype: int64

In [20]:
serd.value_counts()

1    2
2    2
0    1
3    1
Name: count, dtype: int64

In [21]:
serd.isin([2,1])

white      True
white     False
blue       True
green      True
green      True
yellow    False
dtype: bool

In [22]:
serd[serd.isin([2,1])]

white    1
blue     2
green    1
green    2
dtype: int64

In [23]:
import pandas as pd
import numpy as np
s3=pd.Series([1,5,'ab',np.NaN,np.nan,25])
s3

0      1
1      5
2     ab
3    NaN
4    NaN
5     25
dtype: object

In [24]:
s3.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [25]:
s3.notnull()

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [26]:
mydict1={'red':400,'blue':300,'green':600,'white':900}
myseries1=pd.Series(mydict1)
mydict2={'red':300,'brown':100,'green':600,'black':400}
myseries2=pd.Series(mydict2)
myseries2


red      300
brown    100
green    600
black    400
dtype: int64

In [27]:
import pandas as pd
mydict = {'red': 2000, 'blue': 1000, 'yellow': 500, 'orange': 1000}
myseries= pd.Series(mydict)
myseries

red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

In [28]:
myseries1+myseries2

black       NaN
blue        NaN
brown       NaN
green    1200.0
red       700.0
white       NaN
dtype: float64

In [29]:
import pandas as pd
data = {'color' : ['blue','green','yellow','red','white'],
'object' : ['ball','pen','pencil','paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [30]:
frame2 = pd.DataFrame(data, index=['one','two','three','four','five'])
frame2

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

In [31]:
frame2.columns
frame2.values
frame2[1:3]
frame2['object'][3]
print(frame2.loc['two'])


color     green
object      pen
price       1.0
Name: two, dtype: object


C:\Users\YASH SRIVASTAVA\AppData\Local\Temp\ipykernel_24608\3188220635.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  frame2['object'][3]


In [32]:
frame2['new'] = 12
frame2['new'] = [3.0,1.3,2.2,0.8,1.1]
frame2


color  object  price  new
one      blue    ball    1.2  3.0
two     green     pen    1.0  1.3
three  yellow  pencil    0.6  2.2
four      red   paper    0.9  0.8
five    white     mug    1.7  1.1

In [33]:
import pandas as pd 

nestdict = {'red':{2012: 22, 2013: 33},
'white':{2011: 13, 2012: 22, 2013: 16},
'blue': {2011: 17, 2012: 27, 2013: 18}}

frame4 = pd.DataFrame(nestdict)
frame4



red  white  blue
2012  22.0     22    27
2013  33.0     16    18
2011   NaN     13    17

In [34]:
ser = pd.Series([5,0,3,8,4], index=['red','blue','yellow','white','green'])
ser
ser.index
ser.index=['black','blue','yellow','white','green']
ser

black     5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [35]:


ser.idxmax()
ser.index.is_unique
ser.idxmin()
ser.idxmax()

'white'

In [36]:
ser = pd.Series([2,5,7,4], index=['one','two','three','four'])
ser
ser1=ser.reindex(['three','four','five','one','two'])
ser1


three    7.0
four     4.0
five     NaN
one      2.0
two      5.0
dtype: float64

In [37]:
ser3=pd.Series([5,6,3],index=[3,5,6])
ser3


3    5
5    6
6    3
dtype: int64

In [38]:
ser3.reindex(range(6),method='ffill')


0    NaN
1    NaN
2    NaN
3    5.0
4    5.0
5    6.0
dtype: float64

In [39]:
ser3.reindex(range(7),method='bfill')


0    5
1    5
2    5
3    5
4    6
5    6
6    3
dtype: int64

In [40]:
import numpy as np
s1 = pd.Series([3,2,5,1],['white','yellow','green','blue'])
s1.drop('yellow')
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame
frame.drop(['pen','pencil'],axis=1)


ball  paper
red        0      3
blue       4      7
yellow     8     11
white     12     15

In [41]:
s2 = pd.Series([1,4,7,2,1],['white','yellow','black','blue','brown'])
s2

white     1
yellow    4
black     7
blue      2
brown     1
dtype: int64

In [42]:
s1+s2

black     NaN
blue      3.0
brown     NaN
green     NaN
white     4.0
yellow    6.0
dtype: float64

In [43]:
frame1 = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame1
frame2 = pd.DataFrame(np.arange(12).reshape((4,3)),
index=['blue','green','white','yellow'],
columns=['mug','pen','ball'])
frame2
frame1+frame2

ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [44]:
import numpy as np
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame
ser = pd.Series(np.arange(4),  index=['ball','pen','pencil','paper'])
ser

ball      0
pen       1
pencil    2
paper     3
dtype: int32

In [45]:
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [46]:
frame
f = lambda x: x.max() - x.min()
frame.apply(f)


ball      12
pen       12
pencil    12
paper     12
dtype: int32

In [47]:
ser = pd.Series(np.arange(4),  index=['ball','pen','pencil','paper'])
ser

ball      0
pen       1
pencil    2
paper     3
dtype: int32

In [48]:
ser.rank()

ball      1.0
pen       2.0
pencil    3.0
paper     4.0
dtype: float64

In [49]:
frame1


ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [50]:
frame1.sum()

ball      24
pen       28
pencil    32
paper     36
dtype: int64

In [51]:
frame1.sort_index()

ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [52]:
frame1.sort_index()

ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [53]:
frame1.describe()

ball        pen     pencil      paper
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

In [54]:
import pandas as pd
seq = pd.Series([1,2,3,4,4,3,2,1],['2006','2007','2008','2009','2010','2011','2012','2013'])
seq

2006    1
2007    2
2008    3
2009    4
2010    4
2011    3
2012    2
2013    1
dtype: int64

In [55]:
seq2 = pd.Series([3,4,3,4,5,4,3,2],['2006','2007','2008','2009','2010','2011','2012','2013'])
seq2

2006    3
2007    4
2008    3
2009    4
2010    5
2011    4
2012    3
2013    2
dtype: int64

In [56]:
seq.corr(seq2)

0.7745966692414835

In [57]:
seq.cov(seq2)

0.8571428571428571

In [58]:
import numpy as np
ser = pd.Series([0,1,2,np.NaN,9], index=['red','blue','yellow','white','green'])
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [59]:
ser.dropna()

red       0.0
blue      1.0
yellow    2.0
green     9.0
dtype: float64

In [60]:
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [61]:
ser[ser.notnull()]

red       0.0
blue      1.0
yellow    2.0
green     9.0
dtype: float64

In [62]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [63]:
frame3 = pd.DataFrame([[6,np.nan,6],[np.nan,np.nan,np.nan],[2,np.nan,5]],index = ['blue','green','red'],
columns = ['ball','mug','pen'])
frame3

ball  mug  pen
blue    6.0  NaN  6.0
green   NaN  NaN  NaN
red     2.0  NaN  5.0

In [64]:
frame3.dropna()

Empty DataFrame
Columns: [ball, mug, pen]
Index: []

In [65]:
frame3.dropna(how='all')

ball  mug  pen
blue   6.0  NaN  6.0
red    2.0  NaN  5.0

In [66]:
mser = pd.Series(np.random.rand(8), index=[['white','white','white','blue','blue','red','red','red'], 
                                            ['up','down','right','up','down','up','down','left']])
mser


white  up       0.377135
       down     0.890636
       right    0.787149
blue   up       0.695717
       down     0.473675
red    up       0.465092
       down     0.496435
       left     0.206534
dtype: float64

In [67]:
mser.index

MultiIndex([('white',    'up'),
            ('white',  'down'),
            ('white', 'right'),
            ( 'blue',    'up'),
            ( 'blue',  'down'),
            (  'red',    'up'),
            (  'red',  'down'),
            (  'red',  'left')],
           )

In [68]:
mser['white','up']
mser[:,'up']

white    0.377135
blue     0.695717
red      0.465092
dtype: float64

In [69]:
mser.unstack()
mser

white  up       0.377135
       down     0.890636
       right    0.787149
blue   up       0.695717
       down     0.473675
red    up       0.465092
       down     0.496435
       left     0.206534
dtype: float64

In [70]:
mframe = pd.DataFrame(np.random.randn(16).reshape(4,4),
index=[['white','white','red','red'], ['up','down','up','down']],
columns=[['pen','pen','paper','paper'],[1,2,1,2]])
mframe


pen               paper          
                   1         2         1         2
white up   -0.409047 -0.962774  1.531034  0.466679
      down  0.238750  0.863431 -0.109397 -0.344552
red   up    1.059237  0.510029 -0.249685 -0.655995
      down -1.239565  1.329959  0.949953  2.469625

In [71]:
mframe.columns.names = ['objects','id']
mframe.index.names = ['colors','status']
mframe

objects             pen               paper          
id                    1         2         1         2
colors status                                        
white  up     -0.409047 -0.962774  1.531034  0.466679
       down    0.238750  0.863431 -0.109397 -0.344552
red    up      1.059237  0.510029 -0.249685 -0.655995
       down   -1.239565  1.329959  0.949953  2.469625

In [72]:
# mframe.sum(level='colors')
# Using the level keyword in DataFrame and Series aggregations is deprecated and is removed in future versions.
mframe.groupby(level=1).sum()

objects       pen               paper          
id              1         2         1         2
status                                         
down    -1.000815  2.193390  0.840555  2.125073
up       0.650190 -0.452745  1.281350 -0.189317

In [73]:
# mframe.sum(level='id',axis=1)
mframe.T.groupby(level=1).sum()


colors     white                 red          
status        up      down        up      down
id                                            
1       1.121987  0.129353  0.809552 -0.289612
2      -0.496095  0.518879 -0.145966  3.799584