In [1]:
import pandas as pd, numpy as np

In [2]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [3]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'color': ['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [4]:
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [5]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'color': ['white','red','red','black','green'],
'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [6]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [7]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [8]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [9]:
frame2.columns = ['brand','sid']
frame2

brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [10]:
pd.merge(frame1, frame2)

Empty DataFrame
Columns: [id, color, brand, sid]
Index: []

In [11]:
pd.merge(frame1,frame2,how='outer')

id  color   brand  sid
0   pencil    red     ABC  NaN
1      pen    red     ABC  NaN
2     ball  white     OMG  NaN
3      mug  black     POD  NaN
4  ashtray  green     POD  NaN
5      NaN    NaN    ball  ABC
6      NaN    NaN     pen  POD
7      NaN    NaN  pencil  OMG
8      NaN    NaN  pencil  POD

In [12]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id  color brand_x brand_y  sid
0    ball  white     OMG  pencil  OMG
1  pencil    red     ABC  pencil  POD
2     pen    red     ABC    ball  ABC
3     mug  black     POD     pen  POD

In [13]:
frame2.columns = ['brand2','id2']
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

In [14]:
array = np.arange(9).reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
np.concatenate([array,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

1    0.815643
2    0.085490
3    0.158999
4    0.485837
dtype: float64

In [18]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.562138
6    0.031170
7    0.498980
8    0.254909
dtype: float64

In [19]:
pd.concat([ser1,ser2], axis=1)

0         1
1  0.815643       NaN
2  0.085490       NaN
3  0.158999       NaN
4  0.485837       NaN
5       NaN  0.562138
6       NaN  0.031170
7       NaN  0.498980
8       NaN  0.254909

In [20]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.815643
   2    0.085490
   3    0.158999
   4    0.485837
2  5    0.562138
   6    0.031170
   7    0.498980
   8    0.254909
dtype: float64

In [21]:
pd.concat([ser1,ser2], axis=1, keys=[1,2])

1         2
1  0.815643       NaN
2  0.085490       NaN
3  0.158999       NaN
4  0.485837       NaN
5       NaN  0.562138
6       NaN  0.031170
7       NaN  0.498980
8       NaN  0.254909

In [22]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
ser1

1    0.018070
2    0.966071
3    0.020351
4    0.981127
5    0.880321
dtype: float64

In [23]:
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
ser2

2    0.231988
4    0.875687
5    0.320512
6    0.773333
dtype: float64

In [24]:
ser1.combine_first(ser2)

1    0.018070
2    0.966071
3    0.020351
4    0.981127
5    0.880321
6    0.773333
dtype: float64

In [25]:
ser2.combine_first(ser1)

1    0.018070
2    0.231988
3    0.020351
4    0.875687
5    0.320512
6    0.773333
dtype: float64

In [26]:
ser1.combine_first(ser2)

1    0.018070
2    0.966071
3    0.020351
4    0.981127
5    0.880321
6    0.773333
dtype: float64

In [27]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
index=['white','black','red'],
columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [28]:
frame1.stack()

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [29]:
frame1.unstack()

ball    white    0
        black    3
        red      6
pen     white    1
        black    4
        red      7
pencil  white    2
        black    5
        red      8
dtype: int32

In [30]:
longframe = pd.DataFrame({ 'color':['white','white','white',
'red','red','red',
'black','black','black'],
'item':['ball','pen','mug',
'ball','pen','mug',
'ball','pen','mug'],
 'value': np.random.rand(9)})
longframe

color  item     value
0  white  ball  0.547350
1  white   pen  0.155654
2  white   mug  0.477797
3    red  ball  0.266282
4    red   pen  0.225907
5    red   mug  0.781349
6  black  ball  0.075287
7  black   pen  0.909251
8  black   mug  0.583223

In [31]:
wideframe = longframe.pivot('color','item')
wideframe

TypeError: DataFrame.pivot() takes 1 positional argument but 3 were given

In [32]:
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [33]:
#del frame1['ball']
frame3=frame1.drop(['white','black'])
frame3

ball  pen  pencil
red     6    7       8

In [34]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
'value': [2,1,3,3,2]})
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [ ]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [ ]:
dframe[dframe.duplicated()]


color  value
3    red      3
4  white      2

In [ ]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','rosso','verde','black','yellow'],
'price':[5.56,4.20,1.30,0.56,2.75]})
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [ ]:
newcolors = {'pencil': 'red1','black': 'green1' }
newcolors

{'pencil': 'red1', 'black': 'green1'}

In [ ]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3     red1  green1   0.56
4  ashtray  yellow   2.75

In [ ]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [ ]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

In [ ]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','red','green','black','yellow']})
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [ ]:
price = {'ball' : 5.56,'mug' : 4.20,'bottle' : 1.30,'scissors' : 3.41,'pen' : 1.30,'pencil' : 0.56,'ashtray' : 2.75 }
price

{'ball': 5.56,
 'mug': 4.2,
 'bottle': 1.3,
 'scissors': 3.41,
 'pen': 1.3,
 'pencil': 0.56,
 'ashtray': 2.75}

In [ ]:
frame['price'] = frame['item'].map(price)
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [ ]:
reindex = {
0: 'first',1: 'second',2: 'third',3: 'fourth',4: 'fifth'}

In [ ]:
frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [ ]:
recolumn = {'item':'object','price': 'value'}
frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [ ]:
frame.rename(index={1:'first'}, columns={'item':'object'})

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

In [ ]:
frame.rename(columns={'object':'object1'}, inplace=True)
frame

object1   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [ ]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
results

[12, 34, 67, 55, 28, 90, 99, 12, 3, 56, 74, 44, 87, 23, 49, 89, 87]

In [ ]:
bins = [0,25,50,75,100]
bins

[0, 25, 50, 75, 100]

In [ ]:
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [ ]:
cat.dtype

CategoricalDtype(categories=[(0, 25], (25, 50], (50, 75], (75, 100]], ordered=True)

In [ ]:
pd.value_counts(cat)

(75, 100]    5
(0, 25]      4
(25, 50]     4
(50, 75]     4
dtype: int64

In [ ]:
bin_names = ['unlikely','less likely','likely','highly likely']
pd.cut(results, bins, labels=bin_names)

['unlikely', 'less likely', 'likely', 'likely', 'less likely', ..., 'highly likely', 'unlikely', 'less likely', 'highly likely', 'highly likely']
Length: 17
Categories (4, object): ['unlikely' < 'less likely' < 'likely' < 'highly likely']

In [ ]:
cuts=pd.cut(results, 3)
cuts
pd.value_counts(cuts)

(2.904, 35.0]    6
(67.0, 99.0]     6
(35.0, 67.0]     5
dtype: int64

In [ ]:
quintiles = pd.qcut(results, 5)
quintiles

[(2.999, 24.0], (24.0, 46.0], (62.6, 87.0], (46.0, 62.6], (24.0, 46.0], ..., (62.6, 87.0], (2.999, 24.0], (46.0, 62.6], (87.0, 99.0], (62.6, 87.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.999, 24.0] < (24.0, 46.0] < (46.0, 62.6] < (62.6, 87.0] < (87.0, 99.0]]

In [ ]:
pd.value_counts(quintiles)

(2.999, 24.0]    4
(62.6, 87.0]     4
(24.0, 46.0]     3
(46.0, 62.6]     3
(87.0, 99.0]     3
dtype: int64

In [ ]:
randframe = pd.DataFrame(np.random.randn(100,3))
randframe

0         1         2
0  -1.284530 -0.638364  1.316780
1   0.366495  0.503830 -0.608912
2   1.647988  0.638534  0.561866
3  -0.208447 -1.255901  0.229604
4  -1.099663 -1.899511 -0.465291
..       ...       ...       ...
95 -1.282530  0.906099  0.483406
96 -0.773023  0.343799 -0.159807
97 -0.401868  0.245586 -0.152451
98 -1.204984 -1.197060  1.060636
99 -0.287200 -0.768250  0.000558

[100 rows x 3 columns]

In [ ]:
randframe.describe()

0           1           2
count  100.000000  100.000000  100.000000
mean     0.028367   -0.004206   -0.042341
std      1.052400    0.842785    0.865972
min     -2.255820   -1.996598   -1.983760
25%     -0.788634   -0.522009   -0.694638
50%      0.112410    0.088351    0.007539
75%      0.742900    0.654101    0.484793
max      2.231359    1.677520    1.973224

In [ ]:
randframe.std()

0    1.052400
1    0.842785
2    0.865972
dtype: float64

In [ ]:
randframe[(np.abs(randframe) > (2*randframe.std())).any(1)]

C:\Users\MAHE\AppData\Local\Temp\ipykernel_10700\2464754487.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  randframe[(np.abs(randframe) > (2*randframe.std())).any(1)]


0         1         2
4  -1.099663 -1.899511 -0.465291
19 -2.180558  1.013231 -0.689862
20 -2.255820  0.220159 -0.716089
21  0.563983 -0.179704  1.973224
22  1.577704 -1.996598  0.488953
30 -0.848513  0.822491 -1.951790
54  1.871930  0.125010 -1.929396
63  2.231359  0.096996 -0.432499
69  0.135612 -1.826522  0.031355
81  1.621888 -0.115167  1.951665
88 -2.144361 -0.179433 -0.807559
93  0.714790  0.787092 -1.983760

In [ ]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [ ]:
new_order = np.random.permutation(3)
new_order

array([2, 0, 1])

In [ ]:
nframe.take(new_order)

0   1   2   3   4
2  10  11  12  13  14
0   0   1   2   3   4
1   5   6   7   8   9

In [ ]:
new_order = [3,4,2]
nframe.take(new_order)

0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24
2  10  11  12  13  14

In [ ]:
sample = np.random.randint(0, len(nframe), size=4)
sample


array([0, 1, 0, 2])

In [ ]:
nframe.take(sample)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
0   0   1   2   3   4
2  10  11  12  13  14

In [ ]:
text = '16 Bolton Avenue , Boston'


In [ ]:
text.split(',')


['16 Bolton Avenue ', ' Boston']

In [ ]:
address, city = [s.strip() for s in text.split(',')]    
address
city

'Boston'

In [ ]:
text.index('Boston')


19

In [ ]:
text.find('Boston')

19

In [ ]:
address + ',' + city


'16 Bolton Avenue,Boston'

In [ ]:
text.count('e')                     

2

In [ ]:
text.replace('Avenue','Street')


'16 Bolton Street , Boston'

In [ ]:
text = "This is an\t odd \n text!"
text

'This is an\t odd \n text!'

In [ ]:
import re
re.split('\s+', text)

['This', 'is', 'an', 'odd', 'text!']

In [ ]:
regex = re.compile('\s+')    
regex.split(text)


['This', 'is', 'an', 'odd', 'text!']

In [ ]:
text1 = 'This is my address: FC6,CSE Dept, AB5, MIT, Manipal'
text1

'This is my address: FC6,CSE Dept, AB5, MIT, Manipal'

In [ ]:
re.findall('a\w+',text1)

['address', 'anipal']

In [ ]:
re.search('[A,a]\w+',text)

<re.Match object; span=(8, 10), match='an'>

In [ ]:
search = re.search('[A,a]\w+',text)

In [ ]:
search.start()

8

In [ ]:
re.match('T\w+',text)

<re.Match object; span=(0, 4), match='This'>

In [ ]:
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],
'object': ['pen','pencil','pencil','ashtray','pen'],
'price1' : [5.56,4.20,1.30,0.56,2.75],
'price2' : [4.75,4.12,1.60,0.75,3.15]})
frame


color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [ ]:
group = frame['price1'].groupby(frame['color'])
group


In [ ]:
group.groups


{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [ ]:
group.mean()


color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [ ]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

In [ ]:
ggroup = frame['price1'].groupby([frame['color'],frame['object']])
ggroup.groups

{('green', 'pen'): [4], ('green', 'pencil'): [2], ('red', 'ashtray'): [3], ('red', 'pencil'): [1], ('white', 'pen'): [0]}

In [ ]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [ ]:
frame.groupby(frame['color']).mean()

C:\Users\MAHE\AppData\Local\Temp\ipykernel_10700\795964472.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  frame.groupby(frame['color']).mean()


price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [ ]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [ ]:
for name, group in frame.groupby('color'):
    print(name)
    print(group)

green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.12
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen    5.56    4.75


In [ ]:
result1 = frame['price1'].groupby(frame['color']).mean()
result1

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [ ]:
result2 = frame.groupby(frame['color']).mean()
result2

C:\Users\MAHE\AppData\Local\Temp\ipykernel_10700\3251827705.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  result2 = frame.groupby(frame['color']).mean()


price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [ ]:
type(result1)

pandas.core.series.Series

In [ ]:
type(result2)

pandas.core.frame.DataFrame

In [ ]:
(frame.groupby(frame['color']).mean())['price1']

C:\Users\MAHE\AppData\Local\Temp\ipykernel_10700\324963827.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  (frame.groupby(frame['color']).mean())['price1']


color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [ ]:
means = frame.groupby('color').mean().add_prefix('mean_')
means

C:\Users\MAHE\AppData\Local\Temp\ipykernel_13216\198020350.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  means = frame.groupby('color').mean().add_prefix('mean_')


mean_price1  mean_price2
color                          
green        2.025        2.375
red          2.380        2.435
white        5.560        4.750

In [ ]:
group = frame.groupby('color')
group

In [ ]:
group['price1'].quantile(0.6)

color
green    2.170
red      2.744
white    5.560
Name: price1, dtype: float64

In [ ]:
group['price1'].agg('std')

color
green    1.025305
red      2.573869
white         NaN
Name: price1, dtype: float64

In [ ]:
group['price1'].agg('mean')

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [ ]:
frame = pd.DataFrame({ 'color':['white','red','green','red','green'],
'price1':[5.56,4.20,1.30,0.56,2.75],
'price2':[4.75,4.12,1.60,0.75,3.15]})
frame

color  price1  price2
0  white    5.56    4.75
1    red    4.20    4.12
2  green    1.30    1.60
3    red    0.56    0.75
4  green    2.75    3.15

In [ ]:
sums = frame.groupby('color').sum().add_prefix('tot_')
sums

C:\Users\MAHE\AppData\Local\Temp\ipykernel_13216\1661075243.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sums = frame.groupby('color').sum().add_prefix('tot_')


tot_price1  tot_price2
color                        
green        4.05        4.75
red          4.76        4.87
white        5.56        4.75

In [ ]:
frame.groupby('color').transform(np.sum).add_prefix('tot_')

C:\Users\MAHE\AppData\Local\Temp\ipykernel_10700\147351506.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  frame.groupby('color').transform(np.sum).add_prefix('tot_')


tot_price1  tot_price2
0        5.56        4.75
1        4.76        4.87
2        4.05        4.75
3        4.76        4.87
4        4.05        4.75

In [ ]:
frame.groupby(['color']).apply( lambda x: x.max())

color  object  price1  price2
color                               
green  green  pencil    2.75    3.15
red      red  pencil    4.20    4.12
white  white     pen    5.56    4.75